// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemGlobalServicesTest.Models;

#nullable disable

namespace SystemGlobalServicesTest.Migrations
{
    [DbContext(typeof(DBTest))]
    partial class DBTestModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemGlobalServicesTest.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("charCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nominal")
                        .HasColumnType("int");

                    b.Property<int>("numCode")
                        .HasColumnType("int");

                    b.Property<float>("previous")
                        .HasColumnType("real");

                    b.Property<float>("value")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
